### ISSUE TITLE
local installation error

### ISSUE THREAD

**Issue by ggascoigne** [cdaringe/ripcord#56]
14:20 $ npm i -D ripcord
npm WARN prefer global json2csv@3.7.4 should be installed with -g
npm WARN prefer global license-checker@8.0.3 should be installed with -g

> ripcord@0.22.1 install /Users/ggp/dev/tw-git/console/ui/node_modules/ripcord
> node bin/ripcord.js counsel apply

Error: Cannot find global module 'npm'
    at requireg (/Users/ggp/dev/tw-git/console/ui/node_modules/requireg/lib/requireg.js:13:11)
    at Object.<anonymous> (/Users/ggp/dev/tw-git/console/ui/node_modules/ripcord/src/scmcycle.js:6:32)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ggp/dev/tw-git/console/ui/node_modules/ripcord/src/index.js:12:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ggp/dev/tw-git/console/ui/node_modules/ripcord/bin/post-process-report.js:3:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ggp/dev/tw-git/console/ui/node_modules/ripcord/bin/ripcord.js:6:31)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "i" "-D" "ripcord"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! ripcord@0.22.1 install: `node bin/ripcord.js counsel apply`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ripcord@0.22.1 install script 'node bin/ripcord.js counsel apply'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ripcord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/ripcord.js counsel apply
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ripcord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ripcord
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ggp/dev/tw-git/console/ui/npm-debug.log

**Comment by cdaringe** [comment]
this was addressed in some 25.x version
